name: Build Docs

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set up Python 3.7
              uses: actions/setup-python@v1
              with:
                  python-version: 3.7
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pydoc-markdown yapf
                  pip install -e .
            - name: Build docs
              run: |
                  cd docs
                  python generate.py
            - name: Upload docs
              uses: actions/upload-artifact@master
              with:
                  name: "docs"
                  path: docs/
            - name: Commit changes
              uses: EndBug/add-and-commit@master
              with:
                  author_name: Chris Van Pelt
                  author_email: vanpelt@wandb.com
                  message: "Doc updates"
                  path: "."
                  pattern: "docs/*"
                  force: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    deploy:
        runs-on: ubuntu-latest
        if: 'github.ref == "feature/docs"'
        steps:
            - name: "What's here"
              run: ls -al
            - name: "Download docs"
              uses: actions/download-artifact@master
              with:
                  name: docs
            - name: "Print what's here"
              run: ls -al docs
