name: Build Docs

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v
            - name: Set up Python 3.7
              uses: actions/setup-python@v1
              with:
                  python-version: 3.7
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pydoc-markdown yapf
            - name: Build docs
              run: |
                  cd docs
                  python generate.py
